### ISSUE TITLE
panic when dns server is down

### ISSUE THREAD

**Issue by youngking** [benschw/dns-clb-go#3]
-- FAIL: TestGet (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x146263]

goroutine 5 [running]:
testing.func·006()
	/Users/youngking/.gvm/gos/go1.4.2/src/testing/testing.go:441 +0x181
github.com/benschw/dns-clb-go/dns.(*LookupLib).lookup(0xc20800abb0, 0xc20801e0c0, 0x1a, 0x3d59b0, 0x3, 0x3df690, 0x3, 0xc20802a600, 0x0, 0x0)
	/Users/youngking/gspace/src/github.com/benschw/dns-clb-go/dns/lib.go:107 +0x3d3
github.com/benschw/dns-clb-go/dns.(*LookupLib).lookup(0xc20800abb0, 0xc20801e0c0, 0x1a, 0x3d59b0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/youngking/gspace/src/github.com/benschw/dns-clb-go/dns/lib.go:104 +0x39b
github.com/benschw/dns-clb-go/dns.(*LookupLib).lookupType(0xc20800abb0, 0x4228f0, 0x19, 0x3d59b0, 0x3, 0x0, 0x0, 0x0)
	/Users/youngking/gspace/src/github.com/benschw/dns-clb-go/dns/lib.go:85 +0x7c
github.com/benschw/dns-clb-go/dns.(*LookupLib).LookupSRV(0xc20800abb0, 0x4228f0, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/youngking/gspace/src/github.com/benschw/dns-clb-go/dns/lib.go:43 +0xce
github.com/benschw/dns-clb-go/randomclb.(*RandomClb).GetAddress(0xc20800abc0, 0x4228f0, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/youngking/gspace/src/github.com/benschw/dns-clb-go/randomclb/random.go:22 +0xbf

**Comment by benbooth493** [comment]
+1

It needs to return both LoadBalancer and error

**Comment by benschw** [comment]
Sounds good to me, I'll try to take a look at this in the next few days

**Comment by benschw** [comment]
I think I've fixed where the lookup error wasn't propogating after adding a test which I think was reproducing your problem.

https://github.com/benschw/dns-clb-go/commit/fafd1840bd4ed99e2a0305769b6fe7b91571fcb2

would you mind confirming if this covers your problem?

**Comment by youngking** [comment]
It works on me, thanks
